#############################################################################
# Makefile for building: WebKit
# Generated by qmake (3.0) (Qt 5.0.2) on: Fri Jun 7 02:31:51 2013
# Project:  WebKit.pro
# Template: subdirs
# Command: /home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/bin/qmake -Wnone -o Makefile WebKit.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-Source-WTF-WTF-pro \
		sub-Source-JavaScriptCore-JavaScriptCore-pro \
		sub-Source-WebCore-WebCore-pro \
		sub-Source-WebKit-WebKit1-pro \
		sub-Source-QtWebKit-pro \
		sub-Tools-Tools-pro


sub-Source-WTF-WTF-pro-qmake_all:  FORCE
	@test -d Source/WTF/ || mkdir -p Source/WTF/
	cd Source/WTF/ && $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WTF/WTF.pro -Wnone -o Makefile.WTF
	cd Source/WTF/ && $(MAKE) -f Makefile.WTF qmake_all
sub-Source-WTF-WTF-pro: FORCE
	@test -d Source/WTF/ || mkdir -p Source/WTF/
	cd Source/WTF/ && ( test -e Makefile.WTF || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WTF/WTF.pro -Wnone -o Makefile.WTF ) && $(MAKE) -f Makefile.WTF
sub-Source-WTF-WTF-pro-make_first-ordered: FORCE
	@test -d Source/WTF/ || mkdir -p Source/WTF/
	cd Source/WTF/ && ( test -e Makefile.WTF || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WTF/WTF.pro -Wnone -o Makefile.WTF ) && $(MAKE) -f Makefile.WTF 
sub-Source-WTF-WTF-pro-make_first: FORCE
	@test -d Source/WTF/ || mkdir -p Source/WTF/
	cd Source/WTF/ && ( test -e Makefile.WTF || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WTF/WTF.pro -Wnone -o Makefile.WTF ) && $(MAKE) -f Makefile.WTF 
sub-Source-WTF-WTF-pro-all-ordered: FORCE
	@test -d Source/WTF/ || mkdir -p Source/WTF/
	cd Source/WTF/ && ( test -e Makefile.WTF || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WTF/WTF.pro -Wnone -o Makefile.WTF ) && $(MAKE) -f Makefile.WTF all
sub-Source-WTF-WTF-pro-all: FORCE
	@test -d Source/WTF/ || mkdir -p Source/WTF/
	cd Source/WTF/ && ( test -e Makefile.WTF || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WTF/WTF.pro -Wnone -o Makefile.WTF ) && $(MAKE) -f Makefile.WTF all
sub-Source-WTF-WTF-pro-clean-ordered: FORCE
	@test -d Source/WTF/ || mkdir -p Source/WTF/
	cd Source/WTF/ && ( test -e Makefile.WTF || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WTF/WTF.pro -Wnone -o Makefile.WTF ) && $(MAKE) -f Makefile.WTF clean
sub-Source-WTF-WTF-pro-clean: FORCE
	@test -d Source/WTF/ || mkdir -p Source/WTF/
	cd Source/WTF/ && ( test -e Makefile.WTF || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WTF/WTF.pro -Wnone -o Makefile.WTF ) && $(MAKE) -f Makefile.WTF clean
sub-Source-WTF-WTF-pro-distclean-ordered: FORCE
	@test -d Source/WTF/ || mkdir -p Source/WTF/
	cd Source/WTF/ && ( test -e Makefile.WTF || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WTF/WTF.pro -Wnone -o Makefile.WTF ) && $(MAKE) -f Makefile.WTF distclean
sub-Source-WTF-WTF-pro-distclean: FORCE
	@test -d Source/WTF/ || mkdir -p Source/WTF/
	cd Source/WTF/ && ( test -e Makefile.WTF || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WTF/WTF.pro -Wnone -o Makefile.WTF ) && $(MAKE) -f Makefile.WTF distclean
sub-Source-WTF-WTF-pro-install_subtargets-ordered: FORCE
	@test -d Source/WTF/ || mkdir -p Source/WTF/
	cd Source/WTF/ && ( test -e Makefile.WTF || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WTF/WTF.pro -Wnone -o Makefile.WTF ) && $(MAKE) -f Makefile.WTF install
sub-Source-WTF-WTF-pro-install_subtargets: FORCE
	@test -d Source/WTF/ || mkdir -p Source/WTF/
	cd Source/WTF/ && ( test -e Makefile.WTF || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WTF/WTF.pro -Wnone -o Makefile.WTF ) && $(MAKE) -f Makefile.WTF install
sub-Source-WTF-WTF-pro-uninstall_subtargets-ordered: FORCE
	@test -d Source/WTF/ || mkdir -p Source/WTF/
	cd Source/WTF/ && ( test -e Makefile.WTF || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WTF/WTF.pro -Wnone -o Makefile.WTF ) && $(MAKE) -f Makefile.WTF uninstall
sub-Source-WTF-WTF-pro-uninstall_subtargets: FORCE
	@test -d Source/WTF/ || mkdir -p Source/WTF/
	cd Source/WTF/ && ( test -e Makefile.WTF || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WTF/WTF.pro -Wnone -o Makefile.WTF ) && $(MAKE) -f Makefile.WTF uninstall
sub-Source-JavaScriptCore-JavaScriptCore-pro-qmake_all: sub-Source-WTF-WTF-pro-qmake_all FORCE
	@test -d Source/JavaScriptCore/ || mkdir -p Source/JavaScriptCore/
	cd Source/JavaScriptCore/ && $(QMAKE) /home/kanzure/local/qt/WebKit/Source/JavaScriptCore/JavaScriptCore.pro -Wnone -o Makefile.JavaScriptCore
	cd Source/JavaScriptCore/ && $(MAKE) -f Makefile.JavaScriptCore qmake_all
sub-Source-JavaScriptCore-JavaScriptCore-pro: FORCE
	@test -d Source/JavaScriptCore/ || mkdir -p Source/JavaScriptCore/
	cd Source/JavaScriptCore/ && ( test -e Makefile.JavaScriptCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/JavaScriptCore/JavaScriptCore.pro -Wnone -o Makefile.JavaScriptCore ) && $(MAKE) -f Makefile.JavaScriptCore
sub-Source-JavaScriptCore-JavaScriptCore-pro-make_first-ordered: sub-Source-WTF-WTF-pro-make_first-ordered  FORCE
	@test -d Source/JavaScriptCore/ || mkdir -p Source/JavaScriptCore/
	cd Source/JavaScriptCore/ && ( test -e Makefile.JavaScriptCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/JavaScriptCore/JavaScriptCore.pro -Wnone -o Makefile.JavaScriptCore ) && $(MAKE) -f Makefile.JavaScriptCore 
sub-Source-JavaScriptCore-JavaScriptCore-pro-make_first: FORCE
	@test -d Source/JavaScriptCore/ || mkdir -p Source/JavaScriptCore/
	cd Source/JavaScriptCore/ && ( test -e Makefile.JavaScriptCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/JavaScriptCore/JavaScriptCore.pro -Wnone -o Makefile.JavaScriptCore ) && $(MAKE) -f Makefile.JavaScriptCore 
sub-Source-JavaScriptCore-JavaScriptCore-pro-all-ordered: sub-Source-WTF-WTF-pro-all-ordered  FORCE
	@test -d Source/JavaScriptCore/ || mkdir -p Source/JavaScriptCore/
	cd Source/JavaScriptCore/ && ( test -e Makefile.JavaScriptCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/JavaScriptCore/JavaScriptCore.pro -Wnone -o Makefile.JavaScriptCore ) && $(MAKE) -f Makefile.JavaScriptCore all
sub-Source-JavaScriptCore-JavaScriptCore-pro-all: FORCE
	@test -d Source/JavaScriptCore/ || mkdir -p Source/JavaScriptCore/
	cd Source/JavaScriptCore/ && ( test -e Makefile.JavaScriptCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/JavaScriptCore/JavaScriptCore.pro -Wnone -o Makefile.JavaScriptCore ) && $(MAKE) -f Makefile.JavaScriptCore all
sub-Source-JavaScriptCore-JavaScriptCore-pro-clean-ordered: sub-Source-WTF-WTF-pro-clean-ordered  FORCE
	@test -d Source/JavaScriptCore/ || mkdir -p Source/JavaScriptCore/
	cd Source/JavaScriptCore/ && ( test -e Makefile.JavaScriptCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/JavaScriptCore/JavaScriptCore.pro -Wnone -o Makefile.JavaScriptCore ) && $(MAKE) -f Makefile.JavaScriptCore clean
sub-Source-JavaScriptCore-JavaScriptCore-pro-clean: FORCE
	@test -d Source/JavaScriptCore/ || mkdir -p Source/JavaScriptCore/
	cd Source/JavaScriptCore/ && ( test -e Makefile.JavaScriptCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/JavaScriptCore/JavaScriptCore.pro -Wnone -o Makefile.JavaScriptCore ) && $(MAKE) -f Makefile.JavaScriptCore clean
sub-Source-JavaScriptCore-JavaScriptCore-pro-distclean-ordered: sub-Source-WTF-WTF-pro-distclean-ordered  FORCE
	@test -d Source/JavaScriptCore/ || mkdir -p Source/JavaScriptCore/
	cd Source/JavaScriptCore/ && ( test -e Makefile.JavaScriptCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/JavaScriptCore/JavaScriptCore.pro -Wnone -o Makefile.JavaScriptCore ) && $(MAKE) -f Makefile.JavaScriptCore distclean
sub-Source-JavaScriptCore-JavaScriptCore-pro-distclean: FORCE
	@test -d Source/JavaScriptCore/ || mkdir -p Source/JavaScriptCore/
	cd Source/JavaScriptCore/ && ( test -e Makefile.JavaScriptCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/JavaScriptCore/JavaScriptCore.pro -Wnone -o Makefile.JavaScriptCore ) && $(MAKE) -f Makefile.JavaScriptCore distclean
sub-Source-JavaScriptCore-JavaScriptCore-pro-install_subtargets-ordered: sub-Source-WTF-WTF-pro-install_subtargets-ordered  FORCE
	@test -d Source/JavaScriptCore/ || mkdir -p Source/JavaScriptCore/
	cd Source/JavaScriptCore/ && ( test -e Makefile.JavaScriptCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/JavaScriptCore/JavaScriptCore.pro -Wnone -o Makefile.JavaScriptCore ) && $(MAKE) -f Makefile.JavaScriptCore install
sub-Source-JavaScriptCore-JavaScriptCore-pro-install_subtargets: FORCE
	@test -d Source/JavaScriptCore/ || mkdir -p Source/JavaScriptCore/
	cd Source/JavaScriptCore/ && ( test -e Makefile.JavaScriptCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/JavaScriptCore/JavaScriptCore.pro -Wnone -o Makefile.JavaScriptCore ) && $(MAKE) -f Makefile.JavaScriptCore install
sub-Source-JavaScriptCore-JavaScriptCore-pro-uninstall_subtargets-ordered: sub-Source-WTF-WTF-pro-uninstall_subtargets-ordered  FORCE
	@test -d Source/JavaScriptCore/ || mkdir -p Source/JavaScriptCore/
	cd Source/JavaScriptCore/ && ( test -e Makefile.JavaScriptCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/JavaScriptCore/JavaScriptCore.pro -Wnone -o Makefile.JavaScriptCore ) && $(MAKE) -f Makefile.JavaScriptCore uninstall
sub-Source-JavaScriptCore-JavaScriptCore-pro-uninstall_subtargets: FORCE
	@test -d Source/JavaScriptCore/ || mkdir -p Source/JavaScriptCore/
	cd Source/JavaScriptCore/ && ( test -e Makefile.JavaScriptCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/JavaScriptCore/JavaScriptCore.pro -Wnone -o Makefile.JavaScriptCore ) && $(MAKE) -f Makefile.JavaScriptCore uninstall
sub-Source-WebCore-WebCore-pro-qmake_all: sub-Source-JavaScriptCore-JavaScriptCore-pro-qmake_all FORCE
	@test -d Source/WebCore/ || mkdir -p Source/WebCore/
	cd Source/WebCore/ && $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebCore/WebCore.pro -Wnone -o Makefile.WebCore
	cd Source/WebCore/ && $(MAKE) -f Makefile.WebCore qmake_all
sub-Source-WebCore-WebCore-pro: FORCE
	@test -d Source/WebCore/ || mkdir -p Source/WebCore/
	cd Source/WebCore/ && ( test -e Makefile.WebCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebCore/WebCore.pro -Wnone -o Makefile.WebCore ) && $(MAKE) -f Makefile.WebCore
sub-Source-WebCore-WebCore-pro-make_first-ordered: sub-Source-JavaScriptCore-JavaScriptCore-pro-make_first-ordered  FORCE
	@test -d Source/WebCore/ || mkdir -p Source/WebCore/
	cd Source/WebCore/ && ( test -e Makefile.WebCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebCore/WebCore.pro -Wnone -o Makefile.WebCore ) && $(MAKE) -f Makefile.WebCore 
sub-Source-WebCore-WebCore-pro-make_first: FORCE
	@test -d Source/WebCore/ || mkdir -p Source/WebCore/
	cd Source/WebCore/ && ( test -e Makefile.WebCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebCore/WebCore.pro -Wnone -o Makefile.WebCore ) && $(MAKE) -f Makefile.WebCore 
sub-Source-WebCore-WebCore-pro-all-ordered: sub-Source-JavaScriptCore-JavaScriptCore-pro-all-ordered  FORCE
	@test -d Source/WebCore/ || mkdir -p Source/WebCore/
	cd Source/WebCore/ && ( test -e Makefile.WebCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebCore/WebCore.pro -Wnone -o Makefile.WebCore ) && $(MAKE) -f Makefile.WebCore all
sub-Source-WebCore-WebCore-pro-all: FORCE
	@test -d Source/WebCore/ || mkdir -p Source/WebCore/
	cd Source/WebCore/ && ( test -e Makefile.WebCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebCore/WebCore.pro -Wnone -o Makefile.WebCore ) && $(MAKE) -f Makefile.WebCore all
sub-Source-WebCore-WebCore-pro-clean-ordered: sub-Source-JavaScriptCore-JavaScriptCore-pro-clean-ordered  FORCE
	@test -d Source/WebCore/ || mkdir -p Source/WebCore/
	cd Source/WebCore/ && ( test -e Makefile.WebCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebCore/WebCore.pro -Wnone -o Makefile.WebCore ) && $(MAKE) -f Makefile.WebCore clean
sub-Source-WebCore-WebCore-pro-clean: FORCE
	@test -d Source/WebCore/ || mkdir -p Source/WebCore/
	cd Source/WebCore/ && ( test -e Makefile.WebCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebCore/WebCore.pro -Wnone -o Makefile.WebCore ) && $(MAKE) -f Makefile.WebCore clean
sub-Source-WebCore-WebCore-pro-distclean-ordered: sub-Source-JavaScriptCore-JavaScriptCore-pro-distclean-ordered  FORCE
	@test -d Source/WebCore/ || mkdir -p Source/WebCore/
	cd Source/WebCore/ && ( test -e Makefile.WebCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebCore/WebCore.pro -Wnone -o Makefile.WebCore ) && $(MAKE) -f Makefile.WebCore distclean
sub-Source-WebCore-WebCore-pro-distclean: FORCE
	@test -d Source/WebCore/ || mkdir -p Source/WebCore/
	cd Source/WebCore/ && ( test -e Makefile.WebCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebCore/WebCore.pro -Wnone -o Makefile.WebCore ) && $(MAKE) -f Makefile.WebCore distclean
sub-Source-WebCore-WebCore-pro-install_subtargets-ordered: sub-Source-JavaScriptCore-JavaScriptCore-pro-install_subtargets-ordered  FORCE
	@test -d Source/WebCore/ || mkdir -p Source/WebCore/
	cd Source/WebCore/ && ( test -e Makefile.WebCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebCore/WebCore.pro -Wnone -o Makefile.WebCore ) && $(MAKE) -f Makefile.WebCore install
sub-Source-WebCore-WebCore-pro-install_subtargets: FORCE
	@test -d Source/WebCore/ || mkdir -p Source/WebCore/
	cd Source/WebCore/ && ( test -e Makefile.WebCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebCore/WebCore.pro -Wnone -o Makefile.WebCore ) && $(MAKE) -f Makefile.WebCore install
sub-Source-WebCore-WebCore-pro-uninstall_subtargets-ordered: sub-Source-JavaScriptCore-JavaScriptCore-pro-uninstall_subtargets-ordered  FORCE
	@test -d Source/WebCore/ || mkdir -p Source/WebCore/
	cd Source/WebCore/ && ( test -e Makefile.WebCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebCore/WebCore.pro -Wnone -o Makefile.WebCore ) && $(MAKE) -f Makefile.WebCore uninstall
sub-Source-WebCore-WebCore-pro-uninstall_subtargets: FORCE
	@test -d Source/WebCore/ || mkdir -p Source/WebCore/
	cd Source/WebCore/ && ( test -e Makefile.WebCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebCore/WebCore.pro -Wnone -o Makefile.WebCore ) && $(MAKE) -f Makefile.WebCore uninstall
sub-Source-WebKit-WebKit1-pro-qmake_all: sub-Source-WebCore-WebCore-pro-qmake_all FORCE
	@test -d Source/WebKit/ || mkdir -p Source/WebKit/
	cd Source/WebKit/ && $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebKit/WebKit1.pro -Wnone -o Makefile.WebKit1
	cd Source/WebKit/ && $(MAKE) -f Makefile.WebKit1 qmake_all
sub-Source-WebKit-WebKit1-pro: FORCE
	@test -d Source/WebKit/ || mkdir -p Source/WebKit/
	cd Source/WebKit/ && ( test -e Makefile.WebKit1 || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebKit/WebKit1.pro -Wnone -o Makefile.WebKit1 ) && $(MAKE) -f Makefile.WebKit1
sub-Source-WebKit-WebKit1-pro-make_first-ordered: sub-Source-WebCore-WebCore-pro-make_first-ordered  FORCE
	@test -d Source/WebKit/ || mkdir -p Source/WebKit/
	cd Source/WebKit/ && ( test -e Makefile.WebKit1 || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebKit/WebKit1.pro -Wnone -o Makefile.WebKit1 ) && $(MAKE) -f Makefile.WebKit1 
sub-Source-WebKit-WebKit1-pro-make_first: FORCE
	@test -d Source/WebKit/ || mkdir -p Source/WebKit/
	cd Source/WebKit/ && ( test -e Makefile.WebKit1 || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebKit/WebKit1.pro -Wnone -o Makefile.WebKit1 ) && $(MAKE) -f Makefile.WebKit1 
sub-Source-WebKit-WebKit1-pro-all-ordered: sub-Source-WebCore-WebCore-pro-all-ordered  FORCE
	@test -d Source/WebKit/ || mkdir -p Source/WebKit/
	cd Source/WebKit/ && ( test -e Makefile.WebKit1 || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebKit/WebKit1.pro -Wnone -o Makefile.WebKit1 ) && $(MAKE) -f Makefile.WebKit1 all
sub-Source-WebKit-WebKit1-pro-all: FORCE
	@test -d Source/WebKit/ || mkdir -p Source/WebKit/
	cd Source/WebKit/ && ( test -e Makefile.WebKit1 || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebKit/WebKit1.pro -Wnone -o Makefile.WebKit1 ) && $(MAKE) -f Makefile.WebKit1 all
sub-Source-WebKit-WebKit1-pro-clean-ordered: sub-Source-WebCore-WebCore-pro-clean-ordered  FORCE
	@test -d Source/WebKit/ || mkdir -p Source/WebKit/
	cd Source/WebKit/ && ( test -e Makefile.WebKit1 || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebKit/WebKit1.pro -Wnone -o Makefile.WebKit1 ) && $(MAKE) -f Makefile.WebKit1 clean
sub-Source-WebKit-WebKit1-pro-clean: FORCE
	@test -d Source/WebKit/ || mkdir -p Source/WebKit/
	cd Source/WebKit/ && ( test -e Makefile.WebKit1 || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebKit/WebKit1.pro -Wnone -o Makefile.WebKit1 ) && $(MAKE) -f Makefile.WebKit1 clean
sub-Source-WebKit-WebKit1-pro-distclean-ordered: sub-Source-WebCore-WebCore-pro-distclean-ordered  FORCE
	@test -d Source/WebKit/ || mkdir -p Source/WebKit/
	cd Source/WebKit/ && ( test -e Makefile.WebKit1 || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebKit/WebKit1.pro -Wnone -o Makefile.WebKit1 ) && $(MAKE) -f Makefile.WebKit1 distclean
sub-Source-WebKit-WebKit1-pro-distclean: FORCE
	@test -d Source/WebKit/ || mkdir -p Source/WebKit/
	cd Source/WebKit/ && ( test -e Makefile.WebKit1 || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebKit/WebKit1.pro -Wnone -o Makefile.WebKit1 ) && $(MAKE) -f Makefile.WebKit1 distclean
sub-Source-WebKit-WebKit1-pro-install_subtargets-ordered: sub-Source-WebCore-WebCore-pro-install_subtargets-ordered  FORCE
	@test -d Source/WebKit/ || mkdir -p Source/WebKit/
	cd Source/WebKit/ && ( test -e Makefile.WebKit1 || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebKit/WebKit1.pro -Wnone -o Makefile.WebKit1 ) && $(MAKE) -f Makefile.WebKit1 install
sub-Source-WebKit-WebKit1-pro-install_subtargets: FORCE
	@test -d Source/WebKit/ || mkdir -p Source/WebKit/
	cd Source/WebKit/ && ( test -e Makefile.WebKit1 || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebKit/WebKit1.pro -Wnone -o Makefile.WebKit1 ) && $(MAKE) -f Makefile.WebKit1 install
sub-Source-WebKit-WebKit1-pro-uninstall_subtargets-ordered: sub-Source-WebCore-WebCore-pro-uninstall_subtargets-ordered  FORCE
	@test -d Source/WebKit/ || mkdir -p Source/WebKit/
	cd Source/WebKit/ && ( test -e Makefile.WebKit1 || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebKit/WebKit1.pro -Wnone -o Makefile.WebKit1 ) && $(MAKE) -f Makefile.WebKit1 uninstall
sub-Source-WebKit-WebKit1-pro-uninstall_subtargets: FORCE
	@test -d Source/WebKit/ || mkdir -p Source/WebKit/
	cd Source/WebKit/ && ( test -e Makefile.WebKit1 || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebKit/WebKit1.pro -Wnone -o Makefile.WebKit1 ) && $(MAKE) -f Makefile.WebKit1 uninstall
sub-Source-QtWebKit-pro-qmake_all: sub-Source-WebKit-WebKit1-pro-qmake_all FORCE
	@test -d Source/ || mkdir -p Source/
	cd Source/ && $(QMAKE) /home/kanzure/local/qt/WebKit/Source/QtWebKit.pro -Wnone -o Makefile.QtWebKit
	cd Source/ && $(MAKE) -f Makefile.QtWebKit qmake_all
sub-Source-QtWebKit-pro: FORCE
	@test -d Source/ || mkdir -p Source/
	cd Source/ && ( test -e Makefile.QtWebKit || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/QtWebKit.pro -Wnone -o Makefile.QtWebKit ) && $(MAKE) -f Makefile.QtWebKit
sub-Source-QtWebKit-pro-make_first-ordered: sub-Source-WebKit-WebKit1-pro-make_first-ordered  FORCE
	@test -d Source/ || mkdir -p Source/
	cd Source/ && ( test -e Makefile.QtWebKit || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/QtWebKit.pro -Wnone -o Makefile.QtWebKit ) && $(MAKE) -f Makefile.QtWebKit 
sub-Source-QtWebKit-pro-make_first: FORCE
	@test -d Source/ || mkdir -p Source/
	cd Source/ && ( test -e Makefile.QtWebKit || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/QtWebKit.pro -Wnone -o Makefile.QtWebKit ) && $(MAKE) -f Makefile.QtWebKit 
sub-Source-QtWebKit-pro-all-ordered: sub-Source-WebKit-WebKit1-pro-all-ordered  FORCE
	@test -d Source/ || mkdir -p Source/
	cd Source/ && ( test -e Makefile.QtWebKit || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/QtWebKit.pro -Wnone -o Makefile.QtWebKit ) && $(MAKE) -f Makefile.QtWebKit all
sub-Source-QtWebKit-pro-all: FORCE
	@test -d Source/ || mkdir -p Source/
	cd Source/ && ( test -e Makefile.QtWebKit || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/QtWebKit.pro -Wnone -o Makefile.QtWebKit ) && $(MAKE) -f Makefile.QtWebKit all
sub-Source-QtWebKit-pro-clean-ordered: sub-Source-WebKit-WebKit1-pro-clean-ordered  FORCE
	@test -d Source/ || mkdir -p Source/
	cd Source/ && ( test -e Makefile.QtWebKit || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/QtWebKit.pro -Wnone -o Makefile.QtWebKit ) && $(MAKE) -f Makefile.QtWebKit clean
sub-Source-QtWebKit-pro-clean: FORCE
	@test -d Source/ || mkdir -p Source/
	cd Source/ && ( test -e Makefile.QtWebKit || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/QtWebKit.pro -Wnone -o Makefile.QtWebKit ) && $(MAKE) -f Makefile.QtWebKit clean
sub-Source-QtWebKit-pro-distclean-ordered: sub-Source-WebKit-WebKit1-pro-distclean-ordered  FORCE
	@test -d Source/ || mkdir -p Source/
	cd Source/ && ( test -e Makefile.QtWebKit || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/QtWebKit.pro -Wnone -o Makefile.QtWebKit ) && $(MAKE) -f Makefile.QtWebKit distclean
sub-Source-QtWebKit-pro-distclean: FORCE
	@test -d Source/ || mkdir -p Source/
	cd Source/ && ( test -e Makefile.QtWebKit || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/QtWebKit.pro -Wnone -o Makefile.QtWebKit ) && $(MAKE) -f Makefile.QtWebKit distclean
sub-Source-QtWebKit-pro-install_subtargets-ordered: sub-Source-WebKit-WebKit1-pro-install_subtargets-ordered  FORCE
	@test -d Source/ || mkdir -p Source/
	cd Source/ && ( test -e Makefile.QtWebKit || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/QtWebKit.pro -Wnone -o Makefile.QtWebKit ) && $(MAKE) -f Makefile.QtWebKit install
sub-Source-QtWebKit-pro-install_subtargets: FORCE
	@test -d Source/ || mkdir -p Source/
	cd Source/ && ( test -e Makefile.QtWebKit || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/QtWebKit.pro -Wnone -o Makefile.QtWebKit ) && $(MAKE) -f Makefile.QtWebKit install
sub-Source-QtWebKit-pro-uninstall_subtargets-ordered: sub-Source-WebKit-WebKit1-pro-uninstall_subtargets-ordered  FORCE
	@test -d Source/ || mkdir -p Source/
	cd Source/ && ( test -e Makefile.QtWebKit || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/QtWebKit.pro -Wnone -o Makefile.QtWebKit ) && $(MAKE) -f Makefile.QtWebKit uninstall
sub-Source-QtWebKit-pro-uninstall_subtargets: FORCE
	@test -d Source/ || mkdir -p Source/
	cd Source/ && ( test -e Makefile.QtWebKit || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/QtWebKit.pro -Wnone -o Makefile.QtWebKit ) && $(MAKE) -f Makefile.QtWebKit uninstall
sub-Tools-Tools-pro-qmake_all: sub-Source-QtWebKit-pro-qmake_all FORCE
	@test -d Tools/ || mkdir -p Tools/
	cd Tools/ && $(QMAKE) /home/kanzure/local/qt/WebKit/Tools/Tools.pro -Wnone -o Makefile.Tools
	cd Tools/ && $(MAKE) -f Makefile.Tools qmake_all
sub-Tools-Tools-pro: FORCE
	@test -d Tools/ || mkdir -p Tools/
	cd Tools/ && ( test -e Makefile.Tools || $(QMAKE) /home/kanzure/local/qt/WebKit/Tools/Tools.pro -Wnone -o Makefile.Tools ) && $(MAKE) -f Makefile.Tools
sub-Tools-Tools-pro-make_first-ordered: sub-Source-QtWebKit-pro-make_first-ordered  FORCE
	@test -d Tools/ || mkdir -p Tools/
	cd Tools/ && ( test -e Makefile.Tools || $(QMAKE) /home/kanzure/local/qt/WebKit/Tools/Tools.pro -Wnone -o Makefile.Tools ) && $(MAKE) -f Makefile.Tools 
sub-Tools-Tools-pro-make_first: FORCE
	@test -d Tools/ || mkdir -p Tools/
	cd Tools/ && ( test -e Makefile.Tools || $(QMAKE) /home/kanzure/local/qt/WebKit/Tools/Tools.pro -Wnone -o Makefile.Tools ) && $(MAKE) -f Makefile.Tools 
sub-Tools-Tools-pro-all-ordered: sub-Source-QtWebKit-pro-all-ordered  FORCE
	@test -d Tools/ || mkdir -p Tools/
	cd Tools/ && ( test -e Makefile.Tools || $(QMAKE) /home/kanzure/local/qt/WebKit/Tools/Tools.pro -Wnone -o Makefile.Tools ) && $(MAKE) -f Makefile.Tools all
sub-Tools-Tools-pro-all: FORCE
	@test -d Tools/ || mkdir -p Tools/
	cd Tools/ && ( test -e Makefile.Tools || $(QMAKE) /home/kanzure/local/qt/WebKit/Tools/Tools.pro -Wnone -o Makefile.Tools ) && $(MAKE) -f Makefile.Tools all
sub-Tools-Tools-pro-clean-ordered: sub-Source-QtWebKit-pro-clean-ordered  FORCE
	@test -d Tools/ || mkdir -p Tools/
	cd Tools/ && ( test -e Makefile.Tools || $(QMAKE) /home/kanzure/local/qt/WebKit/Tools/Tools.pro -Wnone -o Makefile.Tools ) && $(MAKE) -f Makefile.Tools clean
sub-Tools-Tools-pro-clean: FORCE
	@test -d Tools/ || mkdir -p Tools/
	cd Tools/ && ( test -e Makefile.Tools || $(QMAKE) /home/kanzure/local/qt/WebKit/Tools/Tools.pro -Wnone -o Makefile.Tools ) && $(MAKE) -f Makefile.Tools clean
sub-Tools-Tools-pro-distclean-ordered: sub-Source-QtWebKit-pro-distclean-ordered  FORCE
	@test -d Tools/ || mkdir -p Tools/
	cd Tools/ && ( test -e Makefile.Tools || $(QMAKE) /home/kanzure/local/qt/WebKit/Tools/Tools.pro -Wnone -o Makefile.Tools ) && $(MAKE) -f Makefile.Tools distclean
sub-Tools-Tools-pro-distclean: FORCE
	@test -d Tools/ || mkdir -p Tools/
	cd Tools/ && ( test -e Makefile.Tools || $(QMAKE) /home/kanzure/local/qt/WebKit/Tools/Tools.pro -Wnone -o Makefile.Tools ) && $(MAKE) -f Makefile.Tools distclean
sub-Tools-Tools-pro-install_subtargets-ordered: sub-Source-QtWebKit-pro-install_subtargets-ordered  FORCE
	@test -d Tools/ || mkdir -p Tools/
	cd Tools/ && ( test -e Makefile.Tools || $(QMAKE) /home/kanzure/local/qt/WebKit/Tools/Tools.pro -Wnone -o Makefile.Tools ) && $(MAKE) -f Makefile.Tools install
sub-Tools-Tools-pro-install_subtargets: FORCE
	@test -d Tools/ || mkdir -p Tools/
	cd Tools/ && ( test -e Makefile.Tools || $(QMAKE) /home/kanzure/local/qt/WebKit/Tools/Tools.pro -Wnone -o Makefile.Tools ) && $(MAKE) -f Makefile.Tools install
sub-Tools-Tools-pro-uninstall_subtargets-ordered: sub-Source-QtWebKit-pro-uninstall_subtargets-ordered  FORCE
	@test -d Tools/ || mkdir -p Tools/
	cd Tools/ && ( test -e Makefile.Tools || $(QMAKE) /home/kanzure/local/qt/WebKit/Tools/Tools.pro -Wnone -o Makefile.Tools ) && $(MAKE) -f Makefile.Tools uninstall
sub-Tools-Tools-pro-uninstall_subtargets: FORCE
	@test -d Tools/ || mkdir -p Tools/
	cd Tools/ && ( test -e Makefile.Tools || $(QMAKE) /home/kanzure/local/qt/WebKit/Tools/Tools.pro -Wnone -o Makefile.Tools ) && $(MAKE) -f Makefile.Tools uninstall

Makefile: WebKit.pro .qmake.conf .qmake.cache /home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/linux-g++-64/qmake.conf /home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/spec_pre.prf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/common/shell-unix.conf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/common/unix.conf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/common/linux.conf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/common/gcc-base.conf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/common/gcc-base-unix.conf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/common/g++-base.conf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/common/g++-unix.conf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/qconfig.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules-inst/qt_lib_bootstrap.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_lib_bootstrap.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules-inst/qt_lib_concurrent.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_lib_concurrent.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules-inst/qt_lib_core.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_lib_core.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules-inst/qt_lib_gui.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_lib_gui.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules-inst/qt_lib_network.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_lib_network.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules-inst/qt_lib_platformsupport.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_lib_platformsupport.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules-inst/qt_lib_printsupport.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_lib_printsupport.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules-inst/qt_lib_sql.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_lib_sql.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules-inst/qt_lib_testlib.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_lib_testlib.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules-inst/qt_lib_widgets.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_lib_widgets.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules-inst/qt_lib_xml.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_lib_xml.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_plugin_qdirectfb.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_plugin_qico.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_plugin_qlinuxfb.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_plugin_qminimal.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_plugin_qsqlpsql.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_plugin_qxcb.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_tool_moc.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_tool_qdoc.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_tool_rcc.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_tool_syncqt.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_tool_uic.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/qt_functions.prf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/qt_config.prf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/linux-g++-64/qmake.conf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/spec_post.prf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/qmodule.pri \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/qt_build_config.prf \
		.qmake.conf \
		.qmake.cache \
		Tools/qmake/mkspecs/features/features.pri \
		Tools/qmake/mkspecs/features/functions.prf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/exclusive_builds.prf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/default_pre.prf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/unix/default_pre.prf \
		Tools/qmake/mkspecs/features/features.prf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/configure.prf \
		Tools/qmake/mkspecs/features/configure.prf \
		Tools/qmake/mkspecs/features/default_pre.prf \
		Tools/qmake/mkspecs/features/unix/default_pre.prf \
		Tools/qmake/mkspecs/features/webkit_modules.prf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/resolve_config.prf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/default_post.prf \
		Tools/qmake/mkspecs/features/default_post.prf \
		Tools/qmake/mkspecs/features/unix/default_post.prf \
		Tools/qmake/mkspecs/features/production_build.prf \
		Tools/qmake/mkspecs/features/use_all_in_one_files.prf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/link_pkgconfig.prf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/exceptions_off.prf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/qt_docs_targets.prf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/unix/largefile.prf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/unix/gdb_dwarf_index.prf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/wayland-scanner.prf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/testcase_targets.prf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/yacc.prf \
		/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/lex.prf \
		WebKit.pro
	$(QMAKE) -Wnone -o Makefile WebKit.pro
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/spec_pre.prf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/common/shell-unix.conf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/common/unix.conf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/common/linux.conf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/common/gcc-base.conf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/common/gcc-base-unix.conf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/common/g++-base.conf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/common/g++-unix.conf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/qconfig.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules-inst/qt_lib_bootstrap.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_lib_bootstrap.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules-inst/qt_lib_concurrent.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_lib_concurrent.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules-inst/qt_lib_core.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_lib_core.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules-inst/qt_lib_gui.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_lib_gui.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules-inst/qt_lib_network.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_lib_network.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules-inst/qt_lib_platformsupport.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_lib_platformsupport.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules-inst/qt_lib_printsupport.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_lib_printsupport.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules-inst/qt_lib_sql.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_lib_sql.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules-inst/qt_lib_testlib.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_lib_testlib.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules-inst/qt_lib_widgets.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_lib_widgets.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules-inst/qt_lib_xml.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_lib_xml.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_plugin_qdirectfb.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_plugin_qgenericbearer.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_plugin_qico.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_plugin_qlinuxfb.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_plugin_qminimal.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_plugin_qsqlpsql.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_plugin_qxcb.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_tool_moc.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_tool_qdoc.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_tool_rcc.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_tool_syncqt.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/modules/qt_tool_uic.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/qt_functions.prf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/qt_config.prf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/linux-g++-64/qmake.conf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/spec_post.prf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/qmodule.pri:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/qt_build_config.prf:
.qmake.conf:
.qmake.cache:
Tools/qmake/mkspecs/features/features.pri:
Tools/qmake/mkspecs/features/functions.prf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/exclusive_builds.prf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/default_pre.prf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/unix/default_pre.prf:
Tools/qmake/mkspecs/features/features.prf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/configure.prf:
Tools/qmake/mkspecs/features/configure.prf:
Tools/qmake/mkspecs/features/default_pre.prf:
Tools/qmake/mkspecs/features/unix/default_pre.prf:
Tools/qmake/mkspecs/features/webkit_modules.prf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/resolve_config.prf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/default_post.prf:
Tools/qmake/mkspecs/features/default_post.prf:
Tools/qmake/mkspecs/features/unix/default_post.prf:
Tools/qmake/mkspecs/features/production_build.prf:
Tools/qmake/mkspecs/features/use_all_in_one_files.prf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/link_pkgconfig.prf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/exceptions_off.prf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/qt_docs_targets.prf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/unix/largefile.prf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/unix/gdb_dwarf_index.prf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/wayland-scanner.prf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/testcase_targets.prf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/yacc.prf:
/home/kanzure/local/phantomjs/phantomjs-qt5/qtsdk/qtbase/mkspecs/features/lex.prf:
WebKit.pro:
qmake: FORCE
	@$(QMAKE) -Wnone -o Makefile WebKit.pro

qmake_all: sub-Source-WTF-WTF-pro-qmake_all sub-Source-JavaScriptCore-JavaScriptCore-pro-qmake_all sub-Source-WebCore-WebCore-pro-qmake_all sub-Source-WebKit-WebKit1-pro-qmake_all sub-Source-QtWebKit-pro-qmake_all sub-Tools-Tools-pro-qmake_all FORCE

make_first: sub-Source-WTF-WTF-pro-make_first-ordered sub-Source-JavaScriptCore-JavaScriptCore-pro-make_first-ordered sub-Source-WebCore-WebCore-pro-make_first-ordered sub-Source-WebKit-WebKit1-pro-make_first-ordered sub-Source-QtWebKit-pro-make_first-ordered sub-Tools-Tools-pro-make_first-ordered FORCE
all: sub-Source-WTF-WTF-pro-all-ordered sub-Source-JavaScriptCore-JavaScriptCore-pro-all-ordered sub-Source-WebCore-WebCore-pro-all-ordered sub-Source-WebKit-WebKit1-pro-all-ordered sub-Source-QtWebKit-pro-all-ordered sub-Tools-Tools-pro-all-ordered FORCE
clean: sub-Source-WTF-WTF-pro-clean-ordered sub-Source-JavaScriptCore-JavaScriptCore-pro-clean-ordered sub-Source-WebCore-WebCore-pro-clean-ordered sub-Source-WebKit-WebKit1-pro-clean-ordered sub-Source-QtWebKit-pro-clean-ordered sub-Tools-Tools-pro-clean-ordered FORCE
distclean: sub-Source-WTF-WTF-pro-distclean-ordered sub-Source-JavaScriptCore-JavaScriptCore-pro-distclean-ordered sub-Source-WebCore-WebCore-pro-distclean-ordered sub-Source-WebKit-WebKit1-pro-distclean-ordered sub-Source-QtWebKit-pro-distclean-ordered sub-Tools-Tools-pro-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-Source-WTF-WTF-pro-install_subtargets-ordered sub-Source-JavaScriptCore-JavaScriptCore-pro-install_subtargets-ordered sub-Source-WebCore-WebCore-pro-install_subtargets-ordered sub-Source-WebKit-WebKit1-pro-install_subtargets-ordered sub-Source-QtWebKit-pro-install_subtargets-ordered sub-Tools-Tools-pro-install_subtargets-ordered FORCE
uninstall_subtargets: sub-Source-WTF-WTF-pro-uninstall_subtargets-ordered sub-Source-JavaScriptCore-JavaScriptCore-pro-uninstall_subtargets-ordered sub-Source-WebCore-WebCore-pro-uninstall_subtargets-ordered sub-Source-WebKit-WebKit1-pro-uninstall_subtargets-ordered sub-Source-QtWebKit-pro-uninstall_subtargets-ordered sub-Tools-Tools-pro-uninstall_subtargets-ordered FORCE

reconfigure:
	echo > .qmake.cache && $(MAKE) -f $(MAKEFILE) qmake 
	 @echo "WARNING: Reconfiguration likely requires a clean build. You've been warned!\nYou may execute 'make wipeclean' to wipe the build directory.\n"

wipeclean:
	$(COPY_FILE) $(MAKEFILE) .$(MAKEFILE) && rm -Rf * && $(MOVE) .$(MAKEFILE) $(MAKEFILE)

sub-Source-WebKit-WebKit1-pro-docs_ordered:

sub-Source-WebKit-WebKit1-pro-install_docs_ordered:

sub-Source-WebKit-WebKit1-pro-uninstall_docs_ordered:

sub-Source-WebKit-WebKit1-pro-prepare_docs_ordered:

sub-Source-WebKit-WebKit1-pro-generate_docs_ordered:

incremental:
	$(MAKE) -f $(MAKEFILE) qmake_all && $(MAKE) -f $(MAKEFILE)

%.h:
	@echo -n

html_docs:
	$(MAKE) -f $(MAKEFILE) prepare_docs && $(MAKE) -f $(MAKEFILE) generate_docs

docs:
	$(MAKE) -f $(MAKEFILE) html_docs && $(MAKE) -f $(MAKEFILE) qch_docs

sub-Source-WTF-WTF-pro-install_html_docs_ordered:
	@test -d Source/WTF/ || mkdir -p Source/WTF/
	cd Source/WTF/ && ( test -e Makefile.WTF || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WTF/WTF.pro -Wnone -o Makefile.WTF ) && $(MAKE) -f Makefile.WTF install_html_docs
sub-Source-JavaScriptCore-JavaScriptCore-pro-install_html_docs_ordered: sub-Source-WTF-WTF-pro-install_html_docs_ordered 
	@test -d Source/JavaScriptCore/ || mkdir -p Source/JavaScriptCore/
	cd Source/JavaScriptCore/ && ( test -e Makefile.JavaScriptCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/JavaScriptCore/JavaScriptCore.pro -Wnone -o Makefile.JavaScriptCore ) && $(MAKE) -f Makefile.JavaScriptCore install_html_docs
sub-Source-WebCore-WebCore-pro-install_html_docs_ordered: sub-Source-JavaScriptCore-JavaScriptCore-pro-install_html_docs_ordered 
	@test -d Source/WebCore/ || mkdir -p Source/WebCore/
	cd Source/WebCore/ && ( test -e Makefile.WebCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebCore/WebCore.pro -Wnone -o Makefile.WebCore ) && $(MAKE) -f Makefile.WebCore install_html_docs
sub-Source-WebKit-WebKit1-pro-install_html_docs_ordered: sub-Source-WebCore-WebCore-pro-install_html_docs_ordered 
	@test -d Source/WebKit/ || mkdir -p Source/WebKit/
	cd Source/WebKit/ && ( test -e Makefile.WebKit1 || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebKit/WebKit1.pro -Wnone -o Makefile.WebKit1 ) && $(MAKE) -f Makefile.WebKit1 install_html_docs
sub-Source-QtWebKit-pro-install_html_docs_ordered: sub-Source-WebKit-WebKit1-pro-install_html_docs_ordered 
	@test -d Source/ || mkdir -p Source/
	cd Source/ && ( test -e Makefile.QtWebKit || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/QtWebKit.pro -Wnone -o Makefile.QtWebKit ) && $(MAKE) -f Makefile.QtWebKit install_html_docs
sub-Tools-Tools-pro-install_html_docs_ordered: sub-Source-QtWebKit-pro-install_html_docs_ordered 
	@test -d Tools/ || mkdir -p Tools/
	cd Tools/ && ( test -e Makefile.Tools || $(QMAKE) /home/kanzure/local/qt/WebKit/Tools/Tools.pro -Wnone -o Makefile.Tools ) && $(MAKE) -f Makefile.Tools install_html_docs
install_html_docs: sub-Source-WTF-WTF-pro-install_html_docs_ordered sub-Source-JavaScriptCore-JavaScriptCore-pro-install_html_docs_ordered sub-Source-WebCore-WebCore-pro-install_html_docs_ordered sub-Source-WebKit-WebKit1-pro-install_html_docs_ordered sub-Source-QtWebKit-pro-install_html_docs_ordered sub-Tools-Tools-pro-install_html_docs_ordered

sub-Source-WTF-WTF-pro-uninstall_html_docs_ordered:
	@test -d Source/WTF/ || mkdir -p Source/WTF/
	cd Source/WTF/ && ( test -e Makefile.WTF || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WTF/WTF.pro -Wnone -o Makefile.WTF ) && $(MAKE) -f Makefile.WTF uninstall_html_docs
sub-Source-JavaScriptCore-JavaScriptCore-pro-uninstall_html_docs_ordered: sub-Source-WTF-WTF-pro-uninstall_html_docs_ordered 
	@test -d Source/JavaScriptCore/ || mkdir -p Source/JavaScriptCore/
	cd Source/JavaScriptCore/ && ( test -e Makefile.JavaScriptCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/JavaScriptCore/JavaScriptCore.pro -Wnone -o Makefile.JavaScriptCore ) && $(MAKE) -f Makefile.JavaScriptCore uninstall_html_docs
sub-Source-WebCore-WebCore-pro-uninstall_html_docs_ordered: sub-Source-JavaScriptCore-JavaScriptCore-pro-uninstall_html_docs_ordered 
	@test -d Source/WebCore/ || mkdir -p Source/WebCore/
	cd Source/WebCore/ && ( test -e Makefile.WebCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebCore/WebCore.pro -Wnone -o Makefile.WebCore ) && $(MAKE) -f Makefile.WebCore uninstall_html_docs
sub-Source-WebKit-WebKit1-pro-uninstall_html_docs_ordered: sub-Source-WebCore-WebCore-pro-uninstall_html_docs_ordered 
	@test -d Source/WebKit/ || mkdir -p Source/WebKit/
	cd Source/WebKit/ && ( test -e Makefile.WebKit1 || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebKit/WebKit1.pro -Wnone -o Makefile.WebKit1 ) && $(MAKE) -f Makefile.WebKit1 uninstall_html_docs
sub-Source-QtWebKit-pro-uninstall_html_docs_ordered: sub-Source-WebKit-WebKit1-pro-uninstall_html_docs_ordered 
	@test -d Source/ || mkdir -p Source/
	cd Source/ && ( test -e Makefile.QtWebKit || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/QtWebKit.pro -Wnone -o Makefile.QtWebKit ) && $(MAKE) -f Makefile.QtWebKit uninstall_html_docs
sub-Tools-Tools-pro-uninstall_html_docs_ordered: sub-Source-QtWebKit-pro-uninstall_html_docs_ordered 
	@test -d Tools/ || mkdir -p Tools/
	cd Tools/ && ( test -e Makefile.Tools || $(QMAKE) /home/kanzure/local/qt/WebKit/Tools/Tools.pro -Wnone -o Makefile.Tools ) && $(MAKE) -f Makefile.Tools uninstall_html_docs
uninstall_html_docs: sub-Source-WTF-WTF-pro-uninstall_html_docs_ordered sub-Source-JavaScriptCore-JavaScriptCore-pro-uninstall_html_docs_ordered sub-Source-WebCore-WebCore-pro-uninstall_html_docs_ordered sub-Source-WebKit-WebKit1-pro-uninstall_html_docs_ordered sub-Source-QtWebKit-pro-uninstall_html_docs_ordered sub-Tools-Tools-pro-uninstall_html_docs_ordered

sub-Source-WTF-WTF-pro-install_qch_docs_ordered:
	@test -d Source/WTF/ || mkdir -p Source/WTF/
	cd Source/WTF/ && ( test -e Makefile.WTF || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WTF/WTF.pro -Wnone -o Makefile.WTF ) && $(MAKE) -f Makefile.WTF install_qch_docs
sub-Source-JavaScriptCore-JavaScriptCore-pro-install_qch_docs_ordered: sub-Source-WTF-WTF-pro-install_qch_docs_ordered 
	@test -d Source/JavaScriptCore/ || mkdir -p Source/JavaScriptCore/
	cd Source/JavaScriptCore/ && ( test -e Makefile.JavaScriptCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/JavaScriptCore/JavaScriptCore.pro -Wnone -o Makefile.JavaScriptCore ) && $(MAKE) -f Makefile.JavaScriptCore install_qch_docs
sub-Source-WebCore-WebCore-pro-install_qch_docs_ordered: sub-Source-JavaScriptCore-JavaScriptCore-pro-install_qch_docs_ordered 
	@test -d Source/WebCore/ || mkdir -p Source/WebCore/
	cd Source/WebCore/ && ( test -e Makefile.WebCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebCore/WebCore.pro -Wnone -o Makefile.WebCore ) && $(MAKE) -f Makefile.WebCore install_qch_docs
sub-Source-WebKit-WebKit1-pro-install_qch_docs_ordered: sub-Source-WebCore-WebCore-pro-install_qch_docs_ordered 
	@test -d Source/WebKit/ || mkdir -p Source/WebKit/
	cd Source/WebKit/ && ( test -e Makefile.WebKit1 || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebKit/WebKit1.pro -Wnone -o Makefile.WebKit1 ) && $(MAKE) -f Makefile.WebKit1 install_qch_docs
sub-Source-QtWebKit-pro-install_qch_docs_ordered: sub-Source-WebKit-WebKit1-pro-install_qch_docs_ordered 
	@test -d Source/ || mkdir -p Source/
	cd Source/ && ( test -e Makefile.QtWebKit || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/QtWebKit.pro -Wnone -o Makefile.QtWebKit ) && $(MAKE) -f Makefile.QtWebKit install_qch_docs
sub-Tools-Tools-pro-install_qch_docs_ordered: sub-Source-QtWebKit-pro-install_qch_docs_ordered 
	@test -d Tools/ || mkdir -p Tools/
	cd Tools/ && ( test -e Makefile.Tools || $(QMAKE) /home/kanzure/local/qt/WebKit/Tools/Tools.pro -Wnone -o Makefile.Tools ) && $(MAKE) -f Makefile.Tools install_qch_docs
install_qch_docs: sub-Source-WTF-WTF-pro-install_qch_docs_ordered sub-Source-JavaScriptCore-JavaScriptCore-pro-install_qch_docs_ordered sub-Source-WebCore-WebCore-pro-install_qch_docs_ordered sub-Source-WebKit-WebKit1-pro-install_qch_docs_ordered sub-Source-QtWebKit-pro-install_qch_docs_ordered sub-Tools-Tools-pro-install_qch_docs_ordered

sub-Source-WTF-WTF-pro-uninstall_qch_docs_ordered:
	@test -d Source/WTF/ || mkdir -p Source/WTF/
	cd Source/WTF/ && ( test -e Makefile.WTF || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WTF/WTF.pro -Wnone -o Makefile.WTF ) && $(MAKE) -f Makefile.WTF uninstall_qch_docs
sub-Source-JavaScriptCore-JavaScriptCore-pro-uninstall_qch_docs_ordered: sub-Source-WTF-WTF-pro-uninstall_qch_docs_ordered 
	@test -d Source/JavaScriptCore/ || mkdir -p Source/JavaScriptCore/
	cd Source/JavaScriptCore/ && ( test -e Makefile.JavaScriptCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/JavaScriptCore/JavaScriptCore.pro -Wnone -o Makefile.JavaScriptCore ) && $(MAKE) -f Makefile.JavaScriptCore uninstall_qch_docs
sub-Source-WebCore-WebCore-pro-uninstall_qch_docs_ordered: sub-Source-JavaScriptCore-JavaScriptCore-pro-uninstall_qch_docs_ordered 
	@test -d Source/WebCore/ || mkdir -p Source/WebCore/
	cd Source/WebCore/ && ( test -e Makefile.WebCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebCore/WebCore.pro -Wnone -o Makefile.WebCore ) && $(MAKE) -f Makefile.WebCore uninstall_qch_docs
sub-Source-WebKit-WebKit1-pro-uninstall_qch_docs_ordered: sub-Source-WebCore-WebCore-pro-uninstall_qch_docs_ordered 
	@test -d Source/WebKit/ || mkdir -p Source/WebKit/
	cd Source/WebKit/ && ( test -e Makefile.WebKit1 || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebKit/WebKit1.pro -Wnone -o Makefile.WebKit1 ) && $(MAKE) -f Makefile.WebKit1 uninstall_qch_docs
sub-Source-QtWebKit-pro-uninstall_qch_docs_ordered: sub-Source-WebKit-WebKit1-pro-uninstall_qch_docs_ordered 
	@test -d Source/ || mkdir -p Source/
	cd Source/ && ( test -e Makefile.QtWebKit || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/QtWebKit.pro -Wnone -o Makefile.QtWebKit ) && $(MAKE) -f Makefile.QtWebKit uninstall_qch_docs
sub-Tools-Tools-pro-uninstall_qch_docs_ordered: sub-Source-QtWebKit-pro-uninstall_qch_docs_ordered 
	@test -d Tools/ || mkdir -p Tools/
	cd Tools/ && ( test -e Makefile.Tools || $(QMAKE) /home/kanzure/local/qt/WebKit/Tools/Tools.pro -Wnone -o Makefile.Tools ) && $(MAKE) -f Makefile.Tools uninstall_qch_docs
uninstall_qch_docs: sub-Source-WTF-WTF-pro-uninstall_qch_docs_ordered sub-Source-JavaScriptCore-JavaScriptCore-pro-uninstall_qch_docs_ordered sub-Source-WebCore-WebCore-pro-uninstall_qch_docs_ordered sub-Source-WebKit-WebKit1-pro-uninstall_qch_docs_ordered sub-Source-QtWebKit-pro-uninstall_qch_docs_ordered sub-Tools-Tools-pro-uninstall_qch_docs_ordered

sub-Source-QtWebKit-pro-install_docs_ordered: sub-Source-WebKit-WebKit1-pro-install_docs_ordered 
	@test -d Source/ || mkdir -p Source/
	cd Source/ && ( test -e Makefile.QtWebKit || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/QtWebKit.pro -Wnone -o Makefile.QtWebKit ) && $(MAKE) -f Makefile.QtWebKit install_docs
install_docs: sub-Source-QtWebKit-pro-install_docs_ordered

sub-Source-QtWebKit-pro-uninstall_docs_ordered: sub-Source-WebKit-WebKit1-pro-uninstall_docs_ordered 
	@test -d Source/ || mkdir -p Source/
	cd Source/ && ( test -e Makefile.QtWebKit || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/QtWebKit.pro -Wnone -o Makefile.QtWebKit ) && $(MAKE) -f Makefile.QtWebKit uninstall_docs
uninstall_docs: sub-Source-QtWebKit-pro-uninstall_docs_ordered

sub-Source-WTF-WTF-pro-qch_docs_ordered:
	@test -d Source/WTF/ || mkdir -p Source/WTF/
	cd Source/WTF/ && ( test -e Makefile.WTF || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WTF/WTF.pro -Wnone -o Makefile.WTF ) && $(MAKE) -f Makefile.WTF qch_docs
sub-Source-JavaScriptCore-JavaScriptCore-pro-qch_docs_ordered: sub-Source-WTF-WTF-pro-qch_docs_ordered 
	@test -d Source/JavaScriptCore/ || mkdir -p Source/JavaScriptCore/
	cd Source/JavaScriptCore/ && ( test -e Makefile.JavaScriptCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/JavaScriptCore/JavaScriptCore.pro -Wnone -o Makefile.JavaScriptCore ) && $(MAKE) -f Makefile.JavaScriptCore qch_docs
sub-Source-WebCore-WebCore-pro-qch_docs_ordered: sub-Source-JavaScriptCore-JavaScriptCore-pro-qch_docs_ordered 
	@test -d Source/WebCore/ || mkdir -p Source/WebCore/
	cd Source/WebCore/ && ( test -e Makefile.WebCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebCore/WebCore.pro -Wnone -o Makefile.WebCore ) && $(MAKE) -f Makefile.WebCore qch_docs
sub-Source-WebKit-WebKit1-pro-qch_docs_ordered: sub-Source-WebCore-WebCore-pro-qch_docs_ordered 
	@test -d Source/WebKit/ || mkdir -p Source/WebKit/
	cd Source/WebKit/ && ( test -e Makefile.WebKit1 || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebKit/WebKit1.pro -Wnone -o Makefile.WebKit1 ) && $(MAKE) -f Makefile.WebKit1 qch_docs
sub-Source-QtWebKit-pro-qch_docs_ordered: sub-Source-WebKit-WebKit1-pro-qch_docs_ordered 
	@test -d Source/ || mkdir -p Source/
	cd Source/ && ( test -e Makefile.QtWebKit || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/QtWebKit.pro -Wnone -o Makefile.QtWebKit ) && $(MAKE) -f Makefile.QtWebKit qch_docs
sub-Tools-Tools-pro-qch_docs_ordered: sub-Source-QtWebKit-pro-qch_docs_ordered 
	@test -d Tools/ || mkdir -p Tools/
	cd Tools/ && ( test -e Makefile.Tools || $(QMAKE) /home/kanzure/local/qt/WebKit/Tools/Tools.pro -Wnone -o Makefile.Tools ) && $(MAKE) -f Makefile.Tools qch_docs
qch_docs: sub-Source-WTF-WTF-pro-qch_docs_ordered sub-Source-JavaScriptCore-JavaScriptCore-pro-qch_docs_ordered sub-Source-WebCore-WebCore-pro-qch_docs_ordered sub-Source-WebKit-WebKit1-pro-qch_docs_ordered sub-Source-QtWebKit-pro-qch_docs_ordered sub-Tools-Tools-pro-qch_docs_ordered

sub-Source-QtWebKit-pro-prepare_docs_ordered: sub-Source-WebKit-WebKit1-pro-prepare_docs_ordered 
	@test -d Source/ || mkdir -p Source/
	cd Source/ && ( test -e Makefile.QtWebKit || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/QtWebKit.pro -Wnone -o Makefile.QtWebKit ) && $(MAKE) -f Makefile.QtWebKit prepare_docs
prepare_docs: sub-Source-QtWebKit-pro-prepare_docs_ordered

sub-Source-QtWebKit-pro-generate_docs_ordered: sub-Source-WebKit-WebKit1-pro-generate_docs_ordered 
	@test -d Source/ || mkdir -p Source/
	cd Source/ && ( test -e Makefile.QtWebKit || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/QtWebKit.pro -Wnone -o Makefile.QtWebKit ) && $(MAKE) -f Makefile.QtWebKit generate_docs
generate_docs: sub-Source-QtWebKit-pro-generate_docs_ordered

sub-Source-WTF-WTF-pro-check_ordered:
	@test -d Source/WTF/ || mkdir -p Source/WTF/
	cd Source/WTF/ && ( test -e Makefile.WTF || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WTF/WTF.pro -Wnone -o Makefile.WTF ) && $(MAKE) -f Makefile.WTF check
sub-Source-JavaScriptCore-JavaScriptCore-pro-check_ordered: sub-Source-WTF-WTF-pro-check_ordered 
	@test -d Source/JavaScriptCore/ || mkdir -p Source/JavaScriptCore/
	cd Source/JavaScriptCore/ && ( test -e Makefile.JavaScriptCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/JavaScriptCore/JavaScriptCore.pro -Wnone -o Makefile.JavaScriptCore ) && $(MAKE) -f Makefile.JavaScriptCore check
sub-Source-WebCore-WebCore-pro-check_ordered: sub-Source-JavaScriptCore-JavaScriptCore-pro-check_ordered 
	@test -d Source/WebCore/ || mkdir -p Source/WebCore/
	cd Source/WebCore/ && ( test -e Makefile.WebCore || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebCore/WebCore.pro -Wnone -o Makefile.WebCore ) && $(MAKE) -f Makefile.WebCore check
sub-Source-WebKit-WebKit1-pro-check_ordered: sub-Source-WebCore-WebCore-pro-check_ordered 
	@test -d Source/WebKit/ || mkdir -p Source/WebKit/
	cd Source/WebKit/ && ( test -e Makefile.WebKit1 || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/WebKit/WebKit1.pro -Wnone -o Makefile.WebKit1 ) && $(MAKE) -f Makefile.WebKit1 check
sub-Source-QtWebKit-pro-check_ordered: sub-Source-WebKit-WebKit1-pro-check_ordered 
	@test -d Source/ || mkdir -p Source/
	cd Source/ && ( test -e Makefile.QtWebKit || $(QMAKE) /home/kanzure/local/qt/WebKit/Source/QtWebKit.pro -Wnone -o Makefile.QtWebKit ) && $(MAKE) -f Makefile.QtWebKit check
sub-Tools-Tools-pro-check_ordered: sub-Source-QtWebKit-pro-check_ordered 
	@test -d Tools/ || mkdir -p Tools/
	cd Tools/ && ( test -e Makefile.Tools || $(QMAKE) /home/kanzure/local/qt/WebKit/Tools/Tools.pro -Wnone -o Makefile.Tools ) && $(MAKE) -f Makefile.Tools check
check: sub-Source-WTF-WTF-pro-check_ordered sub-Source-JavaScriptCore-JavaScriptCore-pro-check_ordered sub-Source-WebCore-WebCore-pro-check_ordered sub-Source-WebKit-WebKit1-pro-check_ordered sub-Source-QtWebKit-pro-check_ordered sub-Tools-Tools-pro-check_ordered
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

